steps:
  # 도커 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hymn:$COMMIT_SHA', '.']
  
  # 빌드된 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hymn:$COMMIT_SHA']
  
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hymn'  # 서비스 이름
      - '--image'
      - 'gcr.io/$PROJECT_ID/hymn:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # 서울 리전(필요시 변경)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # 공개 접근 허용

images:
  - 'gcr.io/$PROJECT_ID/hymn:$COMMIT_SHA'
